project:
  type: website

website:
  title: "UROP - Spatial Point Patterns"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SodiumYttrium/Spatial_Point_Pattern.git
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



